# Generated by Django 5.2.3 on 2025-08-20 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_is_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='contents',
            new_name='content',
        ),
    ]
